name: Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install linters
        run: |
          luarocks install luacheck
          cargo install stylua --locked || true

      - name: Run luacheck
        run: luacheck .

